@startuml

' config
hide circle
skinparam linetype ortho
left to right direction

' objects
entity "portal" as portal { }
entity "organization" as organization { }
entity "game instance" as game { }
entity "game session" as session { }

entity "portal admin" as padmin { }
entity "org admin" as oadmin { } 
entity "session admin" as sadmin { }
entity "game designer" as designer { }
entity "facilitator" as facilitator { }
entity "data analyst" as analyst { }
entity "game player" as player { }

' relations
game ||--o{ session
portal ||--{ padmin
portal ||--o{ organization
organization ||-o{ oadmin
organization ||-o{ session
session ||--{ player
session ||--{ facilitator
session ||--o{ sadmin
organization ||--{ session
designer }o--o{ game
game }o--o{ analyst

@enduml
