@startuml

' config
hide circle
skinparam linetype ortho
left to right direction

' objects
entity "portal" as portal #back:lightgreen
entity "organization" as organization #back:lightgreen
entity "game instance" as game #back:lightgreen
entity "game session" as session #back:lightgreen

entity "portal admin" as padmin #back:lightblue
entity "org admin" as oadmin #back:lightblue 
entity "session admin" as sadmin #back:lightblue
entity "game designer" as designer #back:lightblue
entity "facilitator" as facilitator #back:lightblue
entity "data analyst" as analyst #back:lightblue
entity "game player" as player #back:lightblue

' relations
game ||--o{ session
portal ||--{ padmin
portal ||--o{ organization
organization ||-o{ oadmin
organization ||-o{ session
session ||--{ player
session ||--{ facilitator
session ||--o{ sadmin
organization ||--{ session
designer }o--o{ game
game }o--o{ analyst

@enduml
