@startuml
left to right direction

"Game designer" as GD
User <|-- GD

User --> (Login)
User --> (Set password)
User --> (Logout)

GD --> (Create game)

GD --> (Clone game)
GD --> (Delete game)

GD --> (Design game) : "         \n\n\n\n\n"
(Design game) --> (Choose game) : "              "
(Design game) --> (Set goals)
(Design game) --> (Set actors)
(Design game) --> (Show defined actors)
(Design game) --> (Show actor map)
(Design game) --> (Set scenario)
(Design game) --> (Show scenario timeline)
(Design game) --> (Set allowable strategies)
(Design game) --> (Set news items)
(Set scenario) --> (Set parameters)
(Set scenario) --> (Set interventions)
(Set actors) --> (Set parameters)

@enduml
