@startuml
left to right direction
 
"Organization-Game admin" as OGA
User <|-- Administrator
Administrator <|-- OGA

User --> (Login)
User --> (Set password)
User --> (Logout)

Administrator --> (User administration)
note bottom
  - player
  - facilitator
end note

(User administration) --> (Create user)
(User administration) --> (Delete user)
(User administration) --> (Reset user password)
(User administration) --> (Set user access)

"Manage\ngame session" as (Manage)
OGA --> Manage : "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"
Manage --> (Create game session)
Manage --> (Set session dates)
Manage --> (Set allowable strategies)
Manage --> (Delete game session)
Manage --> (Allocate user to game)
Manage --> (Allocate player to game)
Manage --> (Allow self registration\nfor players)
Manage --> (Generate anonymous players)
Manage --> (Show sessions with status)
Manage --> (Show facilitators and\nplayers for session)

@enduml
