@startuml
left to right direction
 
"Session\nFacilitator" as SF
User <|-- Administrator
Administrator <|-- SF

User --> (Login)
User --> (Set password)
User --> (Logout)

Administrator --> (User administration)
note bottom
  player
end note

(User administration) --> (Create player)
(User administration) --> (Delete player)
(User administration) --> (Reset player password)

SF --> (User allocation)
(User allocation) --> (Allocate user to session)
(User allocation) --> (Deallocate user from session)
(User allocation) --> (Show players for session)

"Manage\ngame session" as (Manage)
SF --> Manage
Manage --> (Set session dates)
Manage --> (Allow self registration\nfor players)
Manage --> (Set allowable strategies)
Manage --> (Generate anonymous players)

SF --> (Brief game)

SF --> (Start/stop game session)
(Start/stop game session) --> (Start game session)
(Start/stop game session) --> (Change game speed)
(Start/stop game session) --> (Pause game session)
(Start/stop game session) --> (Stop game session)

SF --> (Facilitate session)
(Facilitate session) --> (Add news item)
(Facilitate session) --> (Add event)
(Facilitate session) --> (Trigger event)
(Facilitate session) --> (Chat with players)
(Facilitate session) --> (Show actor map)
(Facilitate session) --> (Show scores)

(Start game session) --> (Send data to\ngame data platform)
(Add news item) --> (Send data to\ngame data platform)
(Add event) --> (Send data to\ngame data platform)
(Trigger event) --> (Send data to\ngame data platform)
(Stop game session) --> (Send data to\ngame data platform)

SF --> (Debrief game)
(Debrief game) --> (Show scores)
(Debrief game) --> (Show gameplay)

@enduml
