-- MySQL Script generated by MySQL Workbench
-- Sat Aug 30 18:56:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gscg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gscg` ;

-- -----------------------------------------------------
-- Schema gscg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gscg` DEFAULT CHARACTER SET utf8 ;
USE `gscg` ;

-- -----------------------------------------------------
-- Table `gscg`.`organization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`organization` ;

CREATE TABLE IF NOT EXISTS `gscg`.`organization` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `logo` MEDIUMBLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`user` ;

CREATE TABLE IF NOT EXISTS `gscg`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `portal_admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`organization_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`organization_role` ;

CREATE TABLE IF NOT EXISTS `gscg`.`organization_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin` TINYINT NOT NULL DEFAULT 0,
  `user_id` INT UNSIGNED NOT NULL,
  `organization_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_organization_role_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_organization_role_organization1_idx` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gscg`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_role_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `gscg`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `archived` TINYINT NOT NULL DEFAULT 0,
  `logo` MEDIUMBLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`page_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`page_list` ;

CREATE TABLE IF NOT EXISTS `gscg`.`page_list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `header_html` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`page` ;

CREATE TABLE IF NOT EXISTS `gscg`.`page` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `html` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`allowed_strategy_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`allowed_strategy_list` ;

CREATE TABLE IF NOT EXISTS `gscg`.`allowed_strategy_list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `header_html` TEXT NULL,
  `page_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_allowed_strategy_list_page1_idx` (`page_id` ASC) VISIBLE,
  CONSTRAINT `fk_allowed_strategy_list_page1`
    FOREIGN KEY (`page_id`)
    REFERENCES `gscg`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_version` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_version` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `archived` TINYINT NOT NULL DEFAULT 0,
  `briefing_page_list_id` INT UNSIGNED NULL,
  `debriefing_page_list_id` INT UNSIGNED NULL,
  `allowed_strategy_list_id` INT UNSIGNED NULL,
  `goal_page_id` INT UNSIGNED NULL,
  `game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_game_version_game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_game_version_page_list1_idx` (`briefing_page_list_id` ASC) VISIBLE,
  INDEX `fk_game_version_page_list2_idx` (`debriefing_page_list_id` ASC) VISIBLE,
  INDEX `fk_game_version_allowed_strategy_list1_idx` (`allowed_strategy_list_id` ASC) VISIBLE,
  INDEX `fk_game_version_page1_idx` (`goal_page_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_version_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gscg`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_version_page_list1`
    FOREIGN KEY (`briefing_page_list_id`)
    REFERENCES `gscg`.`page_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_version_page_list2`
    FOREIGN KEY (`debriefing_page_list_id`)
    REFERENCES `gscg`.`page_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_version_allowed_strategy_list1`
    FOREIGN KEY (`allowed_strategy_list_id`)
    REFERENCES `gscg`.`allowed_strategy_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_version_page1`
    FOREIGN KEY (`goal_page_id`)
    REFERENCES `gscg`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_role` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin` TINYINT NOT NULL DEFAULT 0,
  `user_id` INT UNSIGNED NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_organization_role_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_game_role_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_role_user0`
    FOREIGN KEY (`user_id`)
    REFERENCES `gscg`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_role_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gscg`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`organization_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`organization_game` ;

CREATE TABLE IF NOT EXISTS `gscg`.`organization_game` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  `organization_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_organization_game_game1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_organization_game_organization1_idx` (`organization_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_game_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gscg`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_game_organization1`
    FOREIGN KEY (`organization_id`)
    REFERENCES `gscg`.`organization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_session` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_session` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `session_status` VARCHAR(45) NOT NULL,
  `play_date` DATE NULL,
  `valid` TINYINT NOT NULL DEFAULT 1,
  `valid_from` DATETIME NULL,
  `valid_until` DATETIME NULL,
  `self_registration` TINYINT NOT NULL DEFAULT 0,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(45) NULL,
  `allow_strategy_choice` TINYINT NOT NULL DEFAULT 1,
  `archived` TINYINT NOT NULL DEFAULT 0,
  `briefing_page_list_id` INT UNSIGNED NULL,
  `debriefing_page_list_id` INT UNSIGNED NULL,
  `allowed_strategy_list_id` INT UNSIGNED NULL,
  `game_version_id` INT UNSIGNED NOT NULL,
  `organization_game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_game_session_game_version1_idx` (`game_version_id` ASC) VISIBLE,
  INDEX `fk_game_session_organization_game1_idx` (`organization_game_id` ASC) VISIBLE,
  INDEX `fk_game_session_page_list1_idx` (`briefing_page_list_id` ASC) VISIBLE,
  INDEX `fk_game_session_page_list2_idx` (`debriefing_page_list_id` ASC) VISIBLE,
  INDEX `fk_game_session_allowed_strategy_list1_idx` (`allowed_strategy_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_session_game_version1`
    FOREIGN KEY (`game_version_id`)
    REFERENCES `gscg`.`game_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_session_organization_game1`
    FOREIGN KEY (`organization_game_id`)
    REFERENCES `gscg`.`organization_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_session_page_list1`
    FOREIGN KEY (`briefing_page_list_id`)
    REFERENCES `gscg`.`page_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_session_page_list2`
    FOREIGN KEY (`debriefing_page_list_id`)
    REFERENCES `gscg`.`page_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_session_allowed_strategy_list1`
    FOREIGN KEY (`allowed_strategy_list_id`)
    REFERENCES `gscg`.`allowed_strategy_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_session_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_session_role` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_session_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `facilitator` TINYINT NOT NULL DEFAULT 0,
  `user_id` INT UNSIGNED NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_organization_role_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_game_session_role_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_role_user00`
    FOREIGN KEY (`user_id`)
    REFERENCES `gscg`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_session_role_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`player` ;

CREATE TABLE IF NOT EXISTS `gscg`.`player` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `display_name` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(45) NULL,
  `blocked` TINYINT NOT NULL DEFAULT 0,
  `game_session_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_player_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  INDEX `fk_player_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gscg`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`actor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`actor_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`actor_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `java_type` VARCHAR(255) NOT NULL,
  `game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_actor_type_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_actor_type_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `gscg`.`game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`landmass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`landmass` ;

CREATE TABLE IF NOT EXISTS `gscg`.`landmass` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `loc_x` DOUBLE NOT NULL,
  `loc_y` DOUBLE NOT NULL,
  `truck_speed` DOUBLE NOT NULL DEFAULT 0.0,
  `speed_unit` VARCHAR(10) NOT NULL DEFAULT 'km/h',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`location` ;

CREATE TABLE IF NOT EXISTS `gscg`.`location` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `loc_x` DOUBLE NOT NULL,
  `loc_y` DOUBLE NOT NULL,
  `timezone_offset` DOUBLE NOT NULL DEFAULT 0,
  `landmass_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_location_landmass1_idx` (`landmass_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_landmass1`
    FOREIGN KEY (`landmass_id`)
    REFERENCES `gscg`.`landmass` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`actor` ;

CREATE TABLE IF NOT EXISTS `gscg`.`actor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `game_version_id` INT UNSIGNED NOT NULL,
  `actor_type_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_actor_game_version1_idx` (`game_version_id` ASC) VISIBLE,
  INDEX `fk_actor_actor_type1_idx` (`actor_type_id` ASC) VISIBLE,
  INDEX `fk_actor_location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_actor_game_version1`
    FOREIGN KEY (`game_version_id`)
    REFERENCES `gscg`.`game_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actor_actor_type1`
    FOREIGN KEY (`actor_type_id`)
    REFERENCES `gscg`.`actor_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actor_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `gscg`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`content_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`content_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `java_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`role_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`role_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`role_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `java_type` VARCHAR(255) NOT NULL,
  `actor_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_actor_role_actor_type1_idx` (`actor_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_actor_role_actor_type1`
    FOREIGN KEY (`actor_type_id`)
    REFERENCES `gscg`.`actor_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `java_type` VARCHAR(255) NOT NULL,
  `role_type_id` INT UNSIGNED NOT NULL,
  `content_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handler_type_content_type1_idx` (`content_type_id` ASC) VISIBLE,
  INDEX `fk_handler_type_role_type1_idx` (`role_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_handler_type_content_type1`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `gscg`.`content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_type_role_type1`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `gscg`.`role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`content_receiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`content_receiver` ;

CREATE TABLE IF NOT EXISTS `gscg`.`content_receiver` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `delay_time` DOUBLE NULL,
  `delay_time_dist` VARCHAR(45) NULL,
  `delay_time_unit` VARCHAR(10) NULL,
  `work_hours_start_mo` TIME NULL DEFAULT 00:00,
  `work_hours_end_mo` TIME NULL DEFAULT 24:00,
  `work_hours_start_tu` TIME NULL DEFAULT 00:00,
  `work_hours_end_tu` TIME NULL DEFAULT 24:00,
  `work_hours_start_we` TIME NULL DEFAULT 00:00,
  `work_hours_end_we` TIME NULL DEFAULT 24:00,
  `work_hours_start_th` TIME NULL DEFAULT 00:00,
  `work_hours_end_th` TIME NULL DEFAULT 24:00,
  `work_hours_start_fr` TIME NULL DEFAULT 00:00,
  `work_hours_end_fr` TIME NULL DEFAULT 24:00,
  `work_hours_start_sa` TIME NULL DEFAULT NULL,
  `work_hours_end_sa` TIME NULL DEFAULT NULL,
  `work_hours_start_su` TIME NULL DEFAULT NULL,
  `work_hours_end_su` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`role` ;

CREATE TABLE IF NOT EXISTS `gscg`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_type_id` INT UNSIGNED NOT NULL,
  `content_receiver_id` INT UNSIGNED NOT NULL,
  `actor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_role_role_type1_idx` (`role_type_id` ASC) VISIBLE,
  INDEX `fk_role_content_receiver1_idx` (`content_receiver_id` ASC) VISIBLE,
  INDEX `fk_role_actor1_idx` (`actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_role_type1`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `gscg`.`role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_content_receiver1`
    FOREIGN KEY (`content_receiver_id`)
    REFERENCES `gscg`.`content_receiver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `gscg`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `handler_type_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handler_handler_type1_idx` (`handler_type_id` ASC) VISIBLE,
  INDEX `fk_handler_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_handler_handler_type1`
    FOREIGN KEY (`handler_type_id`)
    REFERENCES `gscg`.`handler_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `gscg`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`sku` ;

CREATE TABLE IF NOT EXISTS `gscg`.`sku` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `max_volume_m3` DOUBLE NULL,
  `max_weight_kg` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`product` ;

CREATE TABLE IF NOT EXISTS `gscg`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `average_sku_volume` DOUBLE NOT NULL,
  `sku_volume_unit` VARCHAR(10) NOT NULL,
  `average_sku_weight` DOUBLE NOT NULL,
  `sku_weight_unit` VARCHAR(10) NOT NULL,
  `depreciation` DOUBLE NOT NULL DEFAULT 0.0,
  `unit_market_price` DOUBLE NOT NULL DEFAULT 0.0,
  `price_unit` VARCHAR(3) NOT NULL DEFAULT 'USD',
  `game_version_id` INT UNSIGNED NOT NULL,
  `sku_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_product_game_version1_idx` (`game_version_id` ASC) VISIBLE,
  INDEX `fk_product_sku1_idx` (`sku_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_game_version1`
    FOREIGN KEY (`game_version_id`)
    REFERENCES `gscg`.`game_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_sku1`
    FOREIGN KEY (`sku_id`)
    REFERENCES `gscg`.`sku` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`bill_of_materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`bill_of_materials` ;

CREATE TABLE IF NOT EXISTS `gscg`.`bill_of_materials` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_bill_of_materials_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_bill_of_materials_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `gscg`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`bom_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`bom_item` ;

CREATE TABLE IF NOT EXISTS `gscg`.`bom_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL DEFAULT 1.0,
  `product_id` INT UNSIGNED NOT NULL,
  `bill_of_materials_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_bom_item_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_bom_item_bill_of_materials1_idx` (`bill_of_materials_id` ASC) VISIBLE,
  CONSTRAINT `fk_bom_item_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `gscg`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bom_item_bill_of_materials1`
    FOREIGN KEY (`bill_of_materials_id`)
    REFERENCES `gscg`.`bill_of_materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`transport_mode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`transport_mode` ;

CREATE TABLE IF NOT EXISTS `gscg`.`transport_mode` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `average_speed` DOUBLE NOT NULL DEFAULT 0.0,
  `speed_unit` VARCHAR(10) NOT NULL DEFAULT 'km/h',
  `average_handling_time` DOUBLE NOT NULL DEFAULT 0.0,
  `handling_time_unit` VARCHAR(10) NOT NULL DEFAULT 's',
  `continental` TINYINT NOT NULL DEFAULT 1,
  `intercontinental` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handled_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handled_sku` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handled_sku` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sku_id` INT UNSIGNED NOT NULL,
  `transport_mode_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handled_sku_sku1_idx` (`sku_id` ASC) VISIBLE,
  INDEX `fk_handled_sku_transport_mode1_idx` (`transport_mode_id` ASC) VISIBLE,
  CONSTRAINT `fk_handled_sku_sku1`
    FOREIGN KEY (`sku_id`)
    REFERENCES `gscg`.`sku` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handled_sku_transport_mode1`
    FOREIGN KEY (`transport_mode_id`)
    REFERENCES `gscg`.`transport_mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`transfer` ;

CREATE TABLE IF NOT EXISTS `gscg`.`transfer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `distance_km` DOUBLE NOT NULL,
  `travel_time_h` DOUBLE NOT NULL,
  `transport_mode_id` INT UNSIGNED NOT NULL,
  `location1_id` INT UNSIGNED NOT NULL,
  `location2_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_transfer_transport_mode1_idx` (`transport_mode_id` ASC) VISIBLE,
  INDEX `fk_transfer_location1_idx` (`location2_id` ASC) VISIBLE,
  INDEX `fk_transfer_location2_idx` (`location1_id` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_transport_mode1`
    FOREIGN KEY (`transport_mode_id`)
    REFERENCES `gscg`.`transport_mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_location1`
    FOREIGN KEY (`location2_id`)
    REFERENCES `gscg`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_location2`
    FOREIGN KEY (`location1_id`)
    REFERENCES `gscg`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`parameter_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`parameter_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`parameter_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `java_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`actor_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`actor_parameter` ;

CREATE TABLE IF NOT EXISTS `gscg`.`actor_parameter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `default_value` VARCHAR(255) NOT NULL,
  `parameter_type_id` INT UNSIGNED NOT NULL,
  `actor_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parameter_parameter_type1_idx` (`parameter_type_id` ASC) VISIBLE,
  INDEX `fk_actor_parameter_actor_type1_idx` (`actor_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_parameter_parameter_type1`
    FOREIGN KEY (`parameter_type_id`)
    REFERENCES `gscg`.`parameter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actor_parameter_actor_type1`
    FOREIGN KEY (`actor_type_id`)
    REFERENCES `gscg`.`actor_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler_parameter` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler_parameter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `default_value` VARCHAR(255) NOT NULL,
  `parameter_type_id` INT UNSIGNED NOT NULL,
  `handler_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parameter_parameter_type1_idx` (`parameter_type_id` ASC) VISIBLE,
  INDEX `fk_handler_parameter_handler_type1_idx` (`handler_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_parameter_parameter_type10`
    FOREIGN KEY (`parameter_type_id`)
    REFERENCES `gscg`.`parameter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_parameter_handler_type1`
    FOREIGN KEY (`handler_type_id`)
    REFERENCES `gscg`.`handler_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`actor_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`actor_value` ;

CREATE TABLE IF NOT EXISTS `gscg`.`actor_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  `actor_parameter_id` INT UNSIGNED NOT NULL,
  `actor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_actor_value_actor_parameter1_idx` (`actor_parameter_id` ASC) VISIBLE,
  INDEX `fk_actor_value_actor1_idx` (`actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_actor_value_actor_parameter1`
    FOREIGN KEY (`actor_parameter_id`)
    REFERENCES `gscg`.`actor_parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actor_value_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `gscg`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler_value` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  `handler_parameter_id` INT UNSIGNED NOT NULL,
  `handler_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handler_value_handler_parameter1_idx` (`handler_parameter_id` ASC) VISIBLE,
  INDEX `fk_handler_value_handler1_idx` (`handler_id` ASC) VISIBLE,
  CONSTRAINT `fk_handler_value_handler_parameter1`
    FOREIGN KEY (`handler_parameter_id`)
    REFERENCES `gscg`.`handler_parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_value_handler1`
    FOREIGN KEY (`handler_id`)
    REFERENCES `gscg`.`handler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`process_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`process_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`process_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `java_type` VARCHAR(255) NOT NULL,
  `role_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_process_type_role_type1_idx` (`role_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_process_type_role_type1`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `gscg`.`role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`process_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`process_parameter` ;

CREATE TABLE IF NOT EXISTS `gscg`.`process_parameter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `default_value` VARCHAR(255) NOT NULL,
  `parameter_type_id` INT UNSIGNED NOT NULL,
  `process_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parameter_parameter_type1_idx` (`parameter_type_id` ASC) VISIBLE,
  INDEX `fk_process_parameter_process_type1_idx` (`process_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_parameter_parameter_type100`
    FOREIGN KEY (`parameter_type_id`)
    REFERENCES `gscg`.`parameter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_process_parameter_process_type1`
    FOREIGN KEY (`process_type_id`)
    REFERENCES `gscg`.`process_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`process` ;

CREATE TABLE IF NOT EXISTS `gscg`.`process` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `process_type_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_process_process_type1_idx` (`process_type_id` ASC) VISIBLE,
  INDEX `fk_process_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_process_process_type1`
    FOREIGN KEY (`process_type_id`)
    REFERENCES `gscg`.`process_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_process_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `gscg`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`process_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`process_value` ;

CREATE TABLE IF NOT EXISTS `gscg`.`process_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  `process_parameter_id` INT UNSIGNED NOT NULL,
  `process_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_process_value_process_parameter1_idx` (`process_parameter_id` ASC) VISIBLE,
  INDEX `fk_process_value_process1_idx` (`process_id` ASC) VISIBLE,
  CONSTRAINT `fk_process_value_process_parameter1`
    FOREIGN KEY (`process_parameter_id`)
    REFERENCES `gscg`.`process_parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_process_value_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `gscg`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler_valid_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler_valid_product` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler_valid_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `handler_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handler_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_handler_product_handler1_idx` (`handler_id` ASC) VISIBLE,
  CONSTRAINT `fk_handler_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `gscg`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_product_handler1`
    FOREIGN KEY (`handler_id`)
    REFERENCES `gscg`.`handler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler_valid_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler_valid_actor` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler_valid_actor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `handler_id` INT UNSIGNED NOT NULL,
  `actor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handler_product_handler1_idx` (`handler_id` ASC) VISIBLE,
  INDEX `fk_handler_valid_actor_actor1_idx` (`actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_handler_product_handler10`
    FOREIGN KEY (`handler_id`)
    REFERENCES `gscg`.`handler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_valid_actor_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `gscg`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`role_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`role_parameter` ;

CREATE TABLE IF NOT EXISTS `gscg`.`role_parameter` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `default_value` VARCHAR(255) NOT NULL,
  `role_type_id` INT UNSIGNED NOT NULL,
  `parameter_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_role_parameter_role_type1_idx` (`role_type_id` ASC) VISIBLE,
  INDEX `fk_role_parameter_parameter_type1_idx` (`parameter_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_parameter_role_type1`
    FOREIGN KEY (`role_type_id`)
    REFERENCES `gscg`.`role_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_parameter_parameter_type1`
    FOREIGN KEY (`parameter_type_id`)
    REFERENCES `gscg`.`parameter_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`role_value`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`role_value` ;

CREATE TABLE IF NOT EXISTS `gscg`.`role_value` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  `role_parameter_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_role_value_role_parameter1_idx` (`role_parameter_id` ASC) VISIBLE,
  INDEX `fk_role_value_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_value_role_parameter1`
    FOREIGN KEY (`role_parameter_id`)
    REFERENCES `gscg`.`role_parameter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_value_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `gscg`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`trigger_fixed`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`trigger_fixed` ;

CREATE TABLE IF NOT EXISTS `gscg`.`trigger_fixed` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `timestamp_datetime` DATETIME NULL,
  `timestamp_gametime` DOUBLE NULL,
  `timestamp_unit` VARCHAR(10) NULL,
  `facilitator_trigger` TINYINT NOT NULL DEFAULT 0,
  `trigger_once` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`trigger_interval`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`trigger_interval` ;

CREATE TABLE IF NOT EXISTS `gscg`.`trigger_interval` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `timestamp_datetime_start` DATETIME NULL,
  `timestamp_datetime_until` DATETIME NULL,
  `timestamp_gametime_start` DOUBLE NULL,
  `timestamp_gametime_until` DOUBLE NULL,
  `timestamp_unit` VARCHAR(10) NULL,
  `facilitator_trigger` TINYINT NOT NULL DEFAULT 0,
  `trigger_once` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_scenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_scenario` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_scenario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `game_version_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_game_scenario_game_version1_idx` (`game_version_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_scenario_game_version1`
    FOREIGN KEY (`game_version_id`)
    REFERENCES `gscg`.`game_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`news_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`news_message` ;

CREATE TABLE IF NOT EXISTS `gscg`.`news_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `header` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `game_scenario_id` INT UNSIGNED NOT NULL,
  `trigger_fixed_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_news_message_game_scenario1_idx` (`game_scenario_id` ASC) VISIBLE,
  INDEX `fk_news_message_trigger_fixed1_idx` (`trigger_fixed_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_message_game_scenario1`
    FOREIGN KEY (`game_scenario_id`)
    REFERENCES `gscg`.`game_scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_message_trigger_fixed1`
    FOREIGN KEY (`trigger_fixed_id`)
    REFERENCES `gscg`.`trigger_fixed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`event` ;

CREATE TABLE IF NOT EXISTS `gscg`.`event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `object_type` VARCHAR(255) NOT NULL,
  `object_id` INT UNSIGNED NULL,
  `object_name` VARCHAR(45) NULL,
  `object_available` TINYINT NULL,
  `parameter_name` VARCHAR(45) NULL,
  `parameter_value` VARCHAR(255) NULL,
  `trigger_fixed_id` INT UNSIGNED NULL,
  `trigger_interval_id` INT UNSIGNED NULL,
  `game_scenario_id` INT UNSIGNED NOT NULL,
  `news_message_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_event_trigger_fixed1_idx` (`trigger_fixed_id` ASC) VISIBLE,
  INDEX `fk_event_trigger_interval1_idx` (`trigger_interval_id` ASC) VISIBLE,
  INDEX `fk_event_game_scenario1_idx` (`game_scenario_id` ASC) VISIBLE,
  INDEX `fk_event_news_message1_idx` (`news_message_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_trigger_fixed1`
    FOREIGN KEY (`trigger_fixed_id`)
    REFERENCES `gscg`.`trigger_fixed` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_trigger_interval1`
    FOREIGN KEY (`trigger_interval_id`)
    REFERENCES `gscg`.`trigger_interval` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_game_scenario1`
    FOREIGN KEY (`game_scenario_id`)
    REFERENCES `gscg`.`game_scenario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_news_message1`
    FOREIGN KEY (`news_message_id`)
    REFERENCES `gscg`.`news_message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`news_actor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`news_actor_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`news_actor_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `news_message_id` INT UNSIGNED NOT NULL,
  `actor_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `d_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_news_actor_type_news_message1_idx` (`news_message_id` ASC) VISIBLE,
  INDEX `fk_news_actor_type_actor_type1_idx` (`actor_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_actor_type_news_message1`
    FOREIGN KEY (`news_message_id`)
    REFERENCES `gscg`.`news_message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_actor_type_actor_type1`
    FOREIGN KEY (`actor_type_id`)
    REFERENCES `gscg`.`actor_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`news_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`news_actor` ;

CREATE TABLE IF NOT EXISTS `gscg`.`news_actor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `news_message_id` INT UNSIGNED NOT NULL,
  `actor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `d_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_news_actor_type_news_message1_idx` (`news_message_id` ASC) VISIBLE,
  INDEX `fk_news_actor_type_copy1_actor1_idx` (`actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_actor_type_news_message10`
    FOREIGN KEY (`news_message_id`)
    REFERENCES `gscg`.`news_message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_actor_type_copy1_actor1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `gscg`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`organization_game_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`organization_game_role` ;

CREATE TABLE IF NOT EXISTS `gscg`.`organization_game_role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `admin` TINYINT NOT NULL DEFAULT 0,
  `user_id` INT UNSIGNED NOT NULL,
  `organization_game_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_organization_game_role_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_organization_game_role_organization_game1_idx` (`organization_game_id` ASC) VISIBLE,
  CONSTRAINT `fk_organization_game_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gscg`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organization_game_role_organization_game1`
    FOREIGN KEY (`organization_game_id`)
    REFERENCES `gscg`.`organization_game` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`handler_valid_actor_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`handler_valid_actor_type` ;

CREATE TABLE IF NOT EXISTS `gscg`.`handler_valid_actor_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `handler_id` INT UNSIGNED NOT NULL,
  `actor_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_handler_valid_actor_type_handler1_idx` (`handler_id` ASC) VISIBLE,
  INDEX `fk_handler_valid_actor_type_actor_type1_idx` (`actor_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_handler_valid_actor_type_handler1`
    FOREIGN KEY (`handler_id`)
    REFERENCES `gscg`.`handler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_handler_valid_actor_type_actor_type1`
    FOREIGN KEY (`actor_type_id`)
    REFERENCES `gscg`.`actor_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`list_page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`list_page` ;

CREATE TABLE IF NOT EXISTS `gscg`.`list_page` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `html` TEXT NOT NULL,
  `page_list_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_page_page_list1_idx` (`page_list_id` ASC) VISIBLE,
  CONSTRAINT `fk_page_page_list1`
    FOREIGN KEY (`page_list_id`)
    REFERENCES `gscg`.`page_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`goal` ;

CREATE TABLE IF NOT EXISTS `gscg`.`goal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `variable` VARCHAR(255) NOT NULL,
  `min_value` DOUBLE NULL,
  `max_value` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`allowed_strategy_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`allowed_strategy_category` ;

CREATE TABLE IF NOT EXISTS `gscg`.`allowed_strategy_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `header_html` TEXT NULL,
  `page_id` INT UNSIGNED NULL,
  `allowed_strategy_list_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_allowed_strategy_category_allowed_strategy_list1_idx` (`allowed_strategy_list_id` ASC) VISIBLE,
  INDEX `fk_allowed_strategy_category_page1_idx` (`page_id` ASC) VISIBLE,
  CONSTRAINT `fk_allowed_strategy_category_allowed_strategy_list1`
    FOREIGN KEY (`allowed_strategy_list_id`)
    REFERENCES `gscg`.`allowed_strategy_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_allowed_strategy_category_page1`
    FOREIGN KEY (`page_id`)
    REFERENCES `gscg`.`page` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`allowed_strategy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`allowed_strategy` ;

CREATE TABLE IF NOT EXISTS `gscg`.`allowed_strategy` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `explanation_html` TEXT NOT NULL,
  `allowed_strategy_category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_allowed_strategy_allowed_strategy_category1_idx` (`allowed_strategy_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_allowed_strategy_allowed_strategy_category1`
    FOREIGN KEY (`allowed_strategy_category_id`)
    REFERENCES `gscg`.`allowed_strategy_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`chat_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`chat_message` ;

CREATE TABLE IF NOT EXISTS `gscg`.`chat_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `content` TEXT NOT NULL,
  `from_facilitator` TINYINT NOT NULL DEFAULT 0,
  `to_facilitator` TINYINT NOT NULL DEFAULT 0,
  `from_player_id` INT UNSIGNED NULL,
  `to_player_id` INT UNSIGNED NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_chat_message_player1_idx` (`from_player_id` ASC) VISIBLE,
  INDEX `fk_chat_message_player2_idx` (`to_player_id` ASC) VISIBLE,
  INDEX `fk_chat_message_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_message_player1`
    FOREIGN KEY (`from_player_id`)
    REFERENCES `gscg`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_message_player2`
    FOREIGN KEY (`to_player_id`)
    REFERENCES `gscg`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_message_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`chosen_strategy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`chosen_strategy` ;

CREATE TABLE IF NOT EXISTS `gscg`.`chosen_strategy` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `motivation` TEXT NOT NULL,
  `allowed_strategy_id` INT UNSIGNED NOT NULL,
  `player_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_chosen_strategy_allowed_strategy1_idx` (`allowed_strategy_id` ASC) VISIBLE,
  INDEX `fk_chosen_strategy_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_chosen_strategy_allowed_strategy1`
    FOREIGN KEY (`allowed_strategy_id`)
    REFERENCES `gscg`.`allowed_strategy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chosen_strategy_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `gscg`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`triggered_process`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`triggered_process` ;

CREATE TABLE IF NOT EXISTS `gscg`.`triggered_process` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `triggered_facilitator` TINYINT NOT NULL DEFAULT 0,
  `state` TEXT NULL,
  `process_id` INT UNSIGNED NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_triggered_process_process1_idx` (`process_id` ASC) VISIBLE,
  INDEX `fk_triggered_process_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_triggered_process_process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `gscg`.`process` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triggered_process_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`triggered_news_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`triggered_news_message` ;

CREATE TABLE IF NOT EXISTS `gscg`.`triggered_news_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `triggered_facilitator` TINYINT NOT NULL DEFAULT 0,
  `news_message_id` INT UNSIGNED NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_triggered_news_message_news_message1_idx` (`news_message_id` ASC) VISIBLE,
  INDEX `fk_triggered_news_message_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_triggered_news_message_news_message1`
    FOREIGN KEY (`news_message_id`)
    REFERENCES `gscg`.`news_message` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triggered_news_message_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`triggered_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`triggered_event` ;

CREATE TABLE IF NOT EXISTS `gscg`.`triggered_event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `triggered_facilitator` TINYINT NOT NULL DEFAULT 0,
  `state` TEXT NULL,
  `event_id` INT UNSIGNED NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_triggered_event_event1_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_triggered_event_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_triggered_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `gscg`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_triggered_event_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`extra_news_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`extra_news_message` ;

CREATE TABLE IF NOT EXISTS `gscg`.`extra_news_message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `header` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_extra_news_message_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_extra_news_message_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`player_decision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`player_decision` ;

CREATE TABLE IF NOT EXISTS `gscg`.`player_decision` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `state` TEXT NULL,
  `player_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_chosen_strategy_player1_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_chosen_strategy_player10`
    FOREIGN KEY (`player_id`)
    REFERENCES `gscg`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`extra_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`extra_event` ;

CREATE TABLE IF NOT EXISTS `gscg`.`extra_event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `object_type` VARCHAR(255) NOT NULL,
  `object_id` INT NULL,
  `object_name` VARCHAR(45) NULL,
  `object_available` TINYINT NULL,
  `parameter_name` VARCHAR(45) NULL,
  `parameter_value` VARCHAR(255) NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_extra_news_message_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  CONSTRAINT `fk_extra_news_message_game_session10`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`sent_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`sent_content` ;

CREATE TABLE IF NOT EXISTS `gscg`.`sent_content` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `state` TEXT NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  `content_type_id` INT UNSIGNED NOT NULL,
  `from_actor_id` INT UNSIGNED NOT NULL,
  `to_actor_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sent_content_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  INDEX `fk_sent_content_content_type1_idx` (`content_type_id` ASC) VISIBLE,
  INDEX `fk_sent_content_actor1_idx` (`from_actor_id` ASC) VISIBLE,
  INDEX `fk_sent_content_actor2_idx` (`to_actor_id` ASC) VISIBLE,
  CONSTRAINT `fk_sent_content_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sent_content_content_type1`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `gscg`.`content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sent_content_actor1`
    FOREIGN KEY (`from_actor_id`)
    REFERENCES `gscg`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sent_content_actor2`
    FOREIGN KEY (`to_actor_id`)
    REFERENCES `gscg`.`actor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`player_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`player_score` ;

CREATE TABLE IF NOT EXISTS `gscg`.`player_score` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `game_time` DATETIME NOT NULL,
  `wall_time` DATETIME NOT NULL,
  `value` DOUBLE NOT NULL,
  `player_id` INT UNSIGNED NOT NULL,
  `goal_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_player_score_player1_idx` (`player_id` ASC) VISIBLE,
  INDEX `fk_player_score_goal1_idx` (`goal_id` ASC) VISIBLE,
  CONSTRAINT `fk_player_score_player1`
    FOREIGN KEY (`player_id`)
    REFERENCES `gscg`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_player_score_goal1`
    FOREIGN KEY (`goal_id`)
    REFERENCES `gscg`.`goal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_session_goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_session_goal` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_session_goal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `explanation` VARCHAR(45) NOT NULL,
  `game_session_id` INT UNSIGNED NOT NULL,
  `goal_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_session_goal_game_session1_idx` (`game_session_id` ASC) VISIBLE,
  INDEX `fk_session_goal_goal1_idx` (`goal_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_goal_game_session1`
    FOREIGN KEY (`game_session_id`)
    REFERENCES `gscg`.`game_session` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_session_goal_goal1`
    FOREIGN KEY (`goal_id`)
    REFERENCES `gscg`.`goal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gscg`.`game_version_goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gscg`.`game_version_goal` ;

CREATE TABLE IF NOT EXISTS `gscg`.`game_version_goal` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `explanation` VARCHAR(45) NOT NULL,
  `goal_id` INT UNSIGNED NOT NULL,
  `game_version_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_session_goal_goal1_idx` (`goal_id` ASC) VISIBLE,
  INDEX `fk_game_version_goal_game_version1_idx` (`game_version_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_goal_goal10`
    FOREIGN KEY (`goal_id`)
    REFERENCES `gscg`.`goal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_version_goal_game_version1`
    FOREIGN KEY (`game_version_id`)
    REFERENCES `gscg`.`game_version` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
