@startuml
left to right direction

"Game designer" as GD
User <|-- GD

User --> (Set password)

GD --> (Create game)

GD --> (Clone game)

GD --> (Delete game)

GD --> (Design game)
(Design game) --> (Choose game)
(Design game) --> (Set goals)
(Design game) --> (Set actors)
(Design game) --> (View defined actors)
(Design game) --> (Set scenario)
(Design game) --> (View scenario timeline)
(Set scenario) --> (Set parameters)
(Set actors) --> (Set parameters)

@enduml
