@startuml
left to right direction

"Game player" as GP
User <|-- GP

User --> (Set password)

GP --> (Make userid)
GP --> (Login to game)

GP --> (Show briefing)

GP --> (Game play)
(Game play) --> (Show state information) : << extend >>
(Game play) --> (Show news) : << extend >>
(Game play) --> (Make decision) : << extend >>
(Game play) --> (Show actor map\n and highlight player) : << include >>
(Game play) --> (Show scores) : << include >>

(Make decision) --> (Send data to\ngame data platform) : << include >>

GP --> (Show debriefing)

GP --> (Logout from game)

@enduml
