@startuml
left to right direction
 
"Organization\nAdministrator" as OA
User <|-- Administrator
Administrator <|-- OA

User --> (Set password)

Administrator --> (User administration)
note bottom
  - organization member
  - session administrator
  - facilitator
  - player
end note

(User administration) --> (Create user)
(User administration) --> (Delete user)
(User administration) --> (Reset user password)
(User administration) --> (Set user access)

OA --> (Manage organization)
(Manage organization) --> (Change description)
(Manage organization) --> (Change logo)
(Manage organization) --> (Allocate user\nto organization)
(Manage organization) --> (Show games in use)
(Manage organization) --> (Show defined sessions)
(Manage organization) --> (Show allocated users)

@enduml
