@startuml
left to right direction

"Portal Administrator" as PA
User <|-- Administrator
Administrator <|-- PA

User --> (Set password)

Administrator --> (User administration)
note bottom
  all user types
  including super-admin
end note

(User administration) --> (Create user) : << include >>
(User administration) --> (Delete user) : << include >>
(User administration) --> (Reset user password) : << include >>
(User administration) --> (Set user access) : << include >>

PA --> (Manage game)
(Manage game) --> (Create game) : << extend >>
(Manage game) --> (Delete game) : << extend >>
(Manage game) --> (Allocate user\nas game admin) : << extend >>

PA --> (Manage organization)
(Manage organization) --> (Create\norganization) : << extend >>
(Manage organization) --> (Delete\norganization) : << extend >>
(Manage organization) --> (Allocate user as\norganization admin) : << extend >>

@enduml
