@startuml
left to right direction
 
"Portal Administrator" as PA
User <|-- Administrator
Administrator <|-- PA

User --> (Set password)

Administrator --> (User administration)
note bottom
  all user types
  including super-admin
end note

(User administration) --> (Create user)
(User administration) --> (Delete user)
(User administration) --> (Reset user password)
(User administration) --> (Set user access)

PA --> (Manage game)
(Manage game) --> (Create game)
(Manage game) --> (Delete game)
(Manage game) --> (Allocate user\nas game admin)

PA --> (Manage organization)
(Manage organization) --> (Create\norganization)
(Manage organization) --> (Delete\norganization)
(Manage organization) --> (Allocate user as\norganization admin)

@enduml
