@startuml
left to right direction

"Portal Administrator" as PA
User <|-- PA

User --> (Set password)

PA --> (Manage game)
(Manage game) --> (Create game) : << extend >>
(Manage game) --> (Delete game) : << extend >>

PA --> (Manage organization)
(Manage organization) --> (Create\norganization) : << extend >>
(Manage organization) --> (Delete\norganization) : << extend >>
(Manage organization) --> (Allocate user\nto organization) : << extend >>

PA --> (Manage user)
(Manage user) --> (Create user) : << extend >>
(Manage user) --> (Delete user) : << extend >>
(Manage user) --> (Reset\npassword) : << extend >>
(Manage user) --> (Change\naccess) : << extend >>

@enduml
