@startuml
left to right direction

"Session administrator" as SA
User <|-- Administrator
Administrator <|-- SA

User --> (Set password)

Administrator --> (User administration)
note bottom
  player or facilitator
end note

(User administration) --> (Create user) : << include >>
(User administration) --> (Delete user) : << include >>
(User administration) --> (Reset user password) : << include >>
(User administration) --> (Set user access) : << include >>

"Manage\ngame session" as (Manage)
SA --> Manage
Manage --> (Create game session) : << extend >>
Manage --> (Set session dates) : << extend >>
Manage --> (Delete game session) : << extend >>
Manage --> (Show sessions with status) : << extend >>
Manage --> (Show facilitators and\nplayers for session) : << extend >>

@enduml
