@startuml
left to right direction
 
"Session\nFacilitator" as SF
User <|-- Administrator
Administrator <|-- SF

User --> (Set password)

Administrator --> (User administration)
note bottom
  player
end note

(User administration) --> (Create user)
(User administration) --> (Delete user)
(User administration) --> (Reset user password)
(User administration) --> (Set user access)

SF --> (User allocation)
(User allocation) --> (Allocate user to game)
(User allocation) --> (Deallocate user from game)
(User allocation) --> (Show players for session)

SF --> (Brief game)

SF --> (Start/stop game)
(Start/stop game) --> (Start game)
(Start/stop game) --> (Change game speed)
(Start/stop game) --> (Pause game)
(Start/stop game) --> (Stop game)

SF --> (Facilitate session)
(Facilitate session) --> (Add news item)
(Facilitate session) --> (Add intervention)
(Facilitate session) --> (Trigger intervention)
(Facilitate session) --> (Chat with players)
(Facilitate session) --> (Show actor map)
(Facilitate session) --> (Show scores)

(Start game) --> (Send data to\ngame data platform)
(Add news item) --> (Send data to\ngame data platform)
(Add intervention) --> (Send data to\ngame data platform)
(Trigger intervention) --> (Send data to\ngame data platform)
(Stop game) --> (Send data to\ngame data platform)

SF --> (Debrief game)
(Debrief game) --> (Show scores)
(Debrief game) --> (Show gameplay)

@enduml
