@startuml
left to right direction

"Session\nFacilitator" as SF
User <|-- Administrator
Administrator <|-- SF

User --> (Set password)

Administrator --> (User administration)
note bottom
  player
end note

(User administration) --> (Create user) : << include >>
(User administration) --> (Delete user) : << include >>
(User administration) --> (Reset user password) : << include >>
(User administration) --> (Set user access) : << include >>

SF --> (User allocation)
(User allocation) --> (Allocate user to game)
(User allocation) --> (Deallocate user from game)
(User allocation) --> (Show players for session)

SF --> (Brief game)

SF --> (Start/stop game)
(Start/stop game) --> (Start game) : << extend >>
(Start/stop game) --> (Change game speed) : << extend >>
(Start/stop game) --> (Pause game) : << extend >>
(Start/stop game) --> (Stop game) : << extend >>

SF --> (Facilitate session)
(Facilitate session) --> (Add news item) : << extend >>
(Facilitate session) --> (Add intervention) : << extend >>
(Facilitate session) --> (Trigger intervention) : << extend >>
(Facilitate session) --> (Show scores) : << include >>

(Start game) --> (Send data to\ngame data platform) : << include >>
(Add news item) --> (Send data to\ngame data platform) : << include >>
(Add intervention) --> (Send data to\ngame data platform) : << include >>
(Trigger intervention) --> (Send data to\ngame data platform) : << include >>
(Stop game) --> (Send data to\ngame data platform) : << include >>

SF --> (Debrief game)
(Debrief game) --> (Show scores) : << include >>
(Debrief game) --> (Show gameplay) : << extend >>

@enduml
