@startuml
left to right direction

"Session\nFacilitator" as SF
User <|-- SF

User --> (Set password)

SF --> (Brief game)

SF --> (Facilitate users)
(Facilitate users) --> (Allocate user) : << extend >>
(Facilitate users) --> (Deallocate user) : << extend >>

SF --> (Facilitate session)
(Facilitate session) --> (Start game) : << extend >>
(Facilitate session) --> (Change game speed) : << extend >>
(Facilitate session) --> (Add news item) : << extend >>
(Facilitate session) --> (Add intervention) : << extend >>
(Facilitate session) --> (Trigger intervention) : << extend >>
(Facilitate session) --> (Stop game) : << extend >>
(Facilitate session) --> (Show scores) : << iclude >>

(Start game) --> (Send data to\ngame data platform) : << include >>
(Add news item) --> (Send data to\ngame data platform) : << include >>
(Add intervention) --> (Send data to\ngame data platform) : << include >>
(Stop game) --> (Send data to\ngame data platform) : << include >>

SF --> (Debrief game)
(Debrief game) --> (Show scores) : << include >>
(Debrief game) --> (Show gameplay) : << extend >>

@enduml
